photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('post/',views.CreatePhotoView.as_view(),name='post'),#投稿
    path('post_done/',views.PostSuccessView.as_view(),name='post_done'),#投稿完了
    path('photos/<int:category>',views.CategoryView.as_view(),name = 'photos_cat'),

    # ユーザーの投稿一覧ページ
    # photos/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',views.UserView.as_view(),name = 'user_list'),

    path('photo-detail/<int:pk>',views.DetailView.as_view(), name = 'photo_detail'),
    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),
    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',views.PhotoDeleteView.as_view(),name = 'photo_delete'),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photo.urls')),
    path('',include('accounts.urls')),
    path("password_reset/",auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="password_reset",),
    path("password_reset/done/",auth_views.PasswordResetDoneView.as_view(template_name="password_reset_send.html"),name="password_reset_done",),
    path("reset/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name="password_reset_confirm",),
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name="password_reset_complete",),

]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

photo/models.py
from django.db import models

# Create your models here.

from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(verbose_name='カテゴリ',max_length=20)

    def __str__(self):
        return self.title
    
class PhotoPost(models.Model):
# CustomUserモデル(のuser_id)とPhotoPostモデルを
# 1対多の関係で結び付ける
# CustomUserが親でPhotoPostが子の関係となる
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )

# Categoryモデル(のtitle)とPhotoPostモデルを
# 1対多の関係で結び付ける
# Categoryが親でPhotoPostが子の関係となる
    category = models.ForeignKey(
        Category,
        # フィールドのタイトル
        verbose_name='カテゴリ',
        # カテゴリに関連付けられた投稿データが存在する場合は
        # そのカテゴリを削除できないようにする
        on_delete=models.PROTECT
        )
    title = models.CharField(verbose_name='タイトル',max_length=200)

    comment = models.TextField(verbose_name='コメント',)

    image1 = models.ImageField(verbose_name='イメージ1',upload_to = 'photos')

    image2 = models.ImageField(verbose_name='イメージ2',upload_to='photo',blank=True,null=True)

    posted_at = models.DateTimeField(verbose_name='投稿日時',auto_now_add=True)

    def __str__ (self):
        return self.title

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    class Meta:
        # モデルのクラス
        model = PhotoPost
        # フォームで使用するモデルのフィールドを指定
        fields = ['category', 'title', 'comment', 'image1', 'image2']

photo/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import TemplateView,ListView

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost
from django.views.generic import DetailView
from django.views.generic import DeleteView

class IndexView(ListView):
    template_name = 'index.html'
    # モデルPhotoPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 9

class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    template_name = "post_photo.html"
    
    # データベースへの登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name ='post_success.html'

class CategoryView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs["category"]
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(category=category_id).order_by(
            "-posted_at"
        )
        return categories

class UserView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値(ユーザーテーブルのid)を取得
        user_id = self.kwargs["user"]
        # filter(フィールド名=id)で絞り込む
        user_list = PhotoPost.objects.filter(user=user_id).order_by("-posted_at")
        return user_list
    
class DetailView(DetailView):
    template_name='Detail.html'
    model=PhotoPost

class MypageView(ListView):
    template_name = "mypage.html"

    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.filter(user=self.request.user).order_by(
            "-posted_at"
        )

        return queryset
    
class PhotoDeleteView(DeleteView):
    template_name ='photo_delete.html'
    model = PhotoPost

    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        # スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)

photo/templates/base.html
{% load static %}
 
<!doctype html>
<html lang="en">
 
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>{% block title %}{% endblock %}</title>
 
  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
 
 
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
 
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
 
 
</head>
<body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう！</h4>
          <p class="text-muted">
            誰でも参加できる写真投稿サイトです。
            自分で撮影した写真なら何でもオッケー！
            でも、カテゴリに属する写真に限ります。
            コメントも付けてください！
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
            <li><a href="{% url 'photo:mypage' %}" class="text-white">マイページ</a></li>
            <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
            <li><a href="{% url 'password_reset' %}" class="text-white">パスワードのリセット</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
            <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Photo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}{% endblock %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

photo/templates/delete.html
{% extends 'base.html' %}
{% block title %}PhotoDetail{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
            <form method="POST">
                <br>
                <p>削除してもいいですか？</p>
                {% csrf_token %}
                <button class="btn btn-primary my-2" type="submit">削除</button>
                <a href="{% url 'photo:photo_detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
        </div>
    </div>
</div>
{% endblock %}

photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
<br>
<div class="container">
  <div class="row">
    <div class="col offset-3">
      <!-- タイトル -->
       <h2>{{object.title}}</h2>
      <!-- コメント -->
       <p>{{object.comment}}</p>
      <br>
      <!-- 投稿日時 -->
       <p>{{object.posted_at}}に投稿</p>
      <!-- 1枚目の写真 -->
       <p><img src="{{object.imagel.url}}"></p>
      <!-- 2枚目の写真が投稿されていたら表示する-->
       {% if object.image2 %}
       <p><img src="{{ object.image2.url }}"></p>
       {% endif %}
       
       {% if request.user == object.user %}
       <form method="POST">
        <a href="{% url 'photo:photo_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

photo/templates/index.html
{% extends 'base.html' %}
{% block title %}Photo Gallery{% endblock %}

        {% block contents %}
        {% include "photos_title.html" %}
        {% include "photos_list.html" %}
        {% include "pagenation.html" %}
        {% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

{% block contents %}



<!-- ユーザーの投稿件数を表示-->

{% if user.is_authenticated %}
<br>
<div style="text-align:center">
  <h4>{{user.username}}さんのマイページ</h4>
{% if object_list.count == 0 %}
<p>投稿<strong>{{object_list.count}}</strong>件</p>
{% endif %}
  <a href="{% url 'photo:post' %}">投稿する</a>
</div>
<hr>
{% endif %}

<!-- 投稿一覧テンプレートの組み込み-->
{% include "photos_list.html" %}

<!-- ページネーションの組み込み-->
{% include "pagination.html" %}

{% endblock %}

photo/templates/pagenation.html
<ul class="pagenation" style="justify-content:center">
    <!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをorderby_recordsで取得
    Page.has_previous: 直前にページがある場合にTrueを返す
    -->

    {% if page_obj.has_previous %}

    <!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
    Page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--
     すべてのページについてページ番号のアイコンを表示
     paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
     page_obj.paginator.page_rangeとして取得
     ブロックパラメーターnumに順次取り出される
    -->

    {% for num in page_obj.pagenator.page_range %}

    <!--
        各ページのアイコンを出力
        Page.number: 引き渡されたページのページ番号を返す
        -->

        {% if page_obj.number == num %}

    <!--
        処理中のページ番号が引き渡されたページのページ番号と一致する場合は
        ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
        -->
    <li class="page-item active">
        <span class="page-link">{{ num }}</span>
    </li>
    {% else %}
    <!--
        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示
        -->
    <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    <!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next: 次のページがある場合にTrueを返す
    -->

    {% if page_obj.has_next %}

    <!--
    次ページが存在する場合はリンクを設定したアイコン［>>]を表示
    Page.next_page_number: 次のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.imagel.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"> <title>Placeholder</title> <rect width="100%" height="100%" fill="#55595c"/></img>

            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                      {{record.category.title}}
                  </button>
                </div>
                <!-- 投稿したユーザー名を出力-->
                <a href="{% url 'photo:user_list' user=record.user.id %}"><small class="text-muted">{{record.user.username}}</small></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています！</p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="#" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

photo/templates/post_photo.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

{% block contents %}
<br>
<div class="container">
  <div class="row">
    <div class="col offset-2">
      <!-- ファイルをアップロードする場合は
                 enctype="multipart/form-data"が必要 -->
      <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <tr>
          <th>カテゴリ</th>
          <td>{{ form.category }}</td>
        </tr>
        <tr>
          <th>タイトル</th>
          <td>{{ form.title }}</td>
        </tr>
        <tr>
          <th>コメント</th>
          <td>{{ form.comment }}</td>
        </tr>
        <tr>
          <th>画像1</th>
          <td>{{ form.image1 }}</td>
        </tr>
        <tr>
          <th>画像2</th>
          <td>{{ form.image2 }}</td>
        </tr>
      </table>
      <hr>
      <button type="submit">投稿する</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

{% block contents %}
<br><br>
<div class="container">
  <div class="row">
    <div class="col offset-2">
      <h4>投稿が完了しました!</h4>
    </div>
  </div>
</div>
{% endblock %}